using System;
using Avalonia;
using Avalonia.Input;
using Avalonia.Input.Raw;
using Urho.Gui;
using Urho.IO;
using System.Collections.Generic;

using AvaloniaKey = Avalonia.Input.Key;
using UrhoKey = Urho.Key;

namespace Urho.Avalonia
{

    public static class KeyTranslate
    {
        public static Dictionary<UrhoKey, AvaloniaKey> UrhoToAvaloniaKeyMapping = new Dictionary<UrhoKey, AvaloniaKey>()
         {
            {UrhoKey.A,AvaloniaKey.A},
            {UrhoKey.S, AvaloniaKey.S},
            {UrhoKey.D, AvaloniaKey.D},
            {UrhoKey.F, AvaloniaKey.F},
            {UrhoKey.H, AvaloniaKey.H},
            {UrhoKey.G, AvaloniaKey.G},
            {UrhoKey.Z, AvaloniaKey.Z},
            {UrhoKey.X, AvaloniaKey.X},
            {UrhoKey.C, AvaloniaKey.C},
            {UrhoKey.V, AvaloniaKey.V},
            {UrhoKey.B, AvaloniaKey.B},
            {UrhoKey.Q, AvaloniaKey.Q},
            {UrhoKey.W, AvaloniaKey.W},
            {UrhoKey.E, AvaloniaKey.E},
            {UrhoKey.R, AvaloniaKey.R},
            {UrhoKey.Y, AvaloniaKey.Y},
            {UrhoKey.T, AvaloniaKey.T},
            {UrhoKey._1, AvaloniaKey.D1},
            {UrhoKey._2, AvaloniaKey.D2},
            {UrhoKey._3, AvaloniaKey.D3},
            {UrhoKey._4, AvaloniaKey.D4},
            {UrhoKey._6, AvaloniaKey.D6},
            {UrhoKey._5, AvaloniaKey.D5},
            {UrhoKey.Plus, AvaloniaKey.OemPlus},
            {UrhoKey._9, AvaloniaKey.D9},
            {UrhoKey._7, AvaloniaKey.D7},
            {UrhoKey.Minus, AvaloniaKey.OemMinus},
            {UrhoKey._8, AvaloniaKey.D8},
            {UrhoKey._0, AvaloniaKey.D0},
            {UrhoKey.Rightbracket, AvaloniaKey.OemCloseBrackets},
            {UrhoKey.O, AvaloniaKey.O},
            {UrhoKey.U, AvaloniaKey.U},
            {UrhoKey.Leftbracket, AvaloniaKey.OemOpenBrackets},
            {UrhoKey.I, AvaloniaKey.I},
            {UrhoKey.P, AvaloniaKey.P},
            {UrhoKey.L, AvaloniaKey.L},
            {UrhoKey.J, AvaloniaKey.J},
            {UrhoKey.Quote, AvaloniaKey.OemQuotes},
            {UrhoKey.K, AvaloniaKey.K},
            {UrhoKey.Semicolon, AvaloniaKey.OemSemicolon},
            {UrhoKey.Backslash, AvaloniaKey.OemBackslash},
            {UrhoKey.Comma, AvaloniaKey.OemComma},
            {UrhoKey.Slash, AvaloniaKey.Oem2},
            {UrhoKey.N, AvaloniaKey.N},
            {UrhoKey.M, AvaloniaKey.M},
            {UrhoKey.Period, AvaloniaKey.OemPeriod},
        /*  TBD ELI  {UrhoKey.Grave, AvaloniaKey.OemTilde},*/
            {UrhoKey.KpDecimal, AvaloniaKey.Decimal},
            {UrhoKey.KpMultiply, AvaloniaKey.Multiply},
            {UrhoKey.KpPlus, AvaloniaKey.OemPlus},
            {UrhoKey.KpClear, AvaloniaKey.Clear},
            {UrhoKey.KpDivide, AvaloniaKey.Divide},
            {UrhoKey.KpEnter, AvaloniaKey.Enter},
            {UrhoKey.KpMinus, AvaloniaKey.OemMinus},
            {UrhoKey.KpEquals, AvaloniaKey.OemPlus},
            {UrhoKey.Kp0, AvaloniaKey.NumPad0},
            {UrhoKey.Kp1, AvaloniaKey.NumPad1},
            {UrhoKey.Kp2, AvaloniaKey.NumPad2},
            {UrhoKey.Kp3, AvaloniaKey.NumPad3},
            {UrhoKey.Kp4, AvaloniaKey.NumPad4},
            {UrhoKey.Kp5, AvaloniaKey.NumPad5},
            {UrhoKey.Kp6, AvaloniaKey.NumPad6},
            {UrhoKey.Kp7, AvaloniaKey.NumPad7},
            {UrhoKey.Kp8, AvaloniaKey.NumPad8},
            {UrhoKey.Kp9, AvaloniaKey.NumPad9},
            {UrhoKey.Return, AvaloniaKey.Return},
            {UrhoKey.Tab, AvaloniaKey.Tab},
            {UrhoKey.Space, AvaloniaKey.Space},
            {UrhoKey.Backspace, AvaloniaKey.Back},
            {UrhoKey.Escape, AvaloniaKey.Escape},
            {UrhoKey.Gui, AvaloniaKey.LWin},
            {UrhoKey.Shift, AvaloniaKey.LeftShift},
            {UrhoKey.Capslock, AvaloniaKey.CapsLock},
            {UrhoKey.Alt, AvaloniaKey.LeftAlt},
            {UrhoKey.Ctrl, AvaloniaKey.LeftCtrl},
            {UrhoKey.Rgui, AvaloniaKey.RWin},
            {UrhoKey.Rshift, AvaloniaKey.RightShift},
            {UrhoKey.Ralt, AvaloniaKey.RightAlt},
            {UrhoKey.Rctrl, AvaloniaKey.RightCtrl},
            {UrhoKey.F17, AvaloniaKey.F17},
            {UrhoKey.Volumeup, AvaloniaKey.VolumeUp},
            {UrhoKey.Volumedown, AvaloniaKey.VolumeDown},
            {UrhoKey.Mute, AvaloniaKey.VolumeMute},
            {UrhoKey.F18, AvaloniaKey.F18},
            {UrhoKey.F19, AvaloniaKey.F19},
            {UrhoKey.F20, AvaloniaKey.F20},
            {UrhoKey.F5, AvaloniaKey.F5},
            {UrhoKey.F6, AvaloniaKey.F6},
            {UrhoKey.F7, AvaloniaKey.F7},
            {UrhoKey.F3, AvaloniaKey.F3},
            {UrhoKey.F8, AvaloniaKey.F8},
            {UrhoKey.F9, AvaloniaKey.F9},
            {UrhoKey.F11, AvaloniaKey.F11},
            {UrhoKey.F13, AvaloniaKey.F13},
            {UrhoKey.F16, AvaloniaKey.F16},
            {UrhoKey.F14, AvaloniaKey.F14},
            {UrhoKey.F10, AvaloniaKey.F10},
            {UrhoKey.F12, AvaloniaKey.F12},
            {UrhoKey.F15, AvaloniaKey.F15},
            {UrhoKey.Help, AvaloniaKey.Help},
            {UrhoKey.Home, AvaloniaKey.Home},
            {UrhoKey.PageUp, AvaloniaKey.PageUp},
            {UrhoKey.Delete, AvaloniaKey.Delete},
            {UrhoKey.F4, AvaloniaKey.F4},
            {UrhoKey.End, AvaloniaKey.End},
            {UrhoKey.F2, AvaloniaKey.F2},
            {UrhoKey.PageDown, AvaloniaKey.PageDown},
            {UrhoKey.F1, AvaloniaKey.F1},
            {UrhoKey.Left, AvaloniaKey.Left},
            {UrhoKey.Right, AvaloniaKey.Right},
            {UrhoKey.Down, AvaloniaKey.Down},
            {UrhoKey.Up, AvaloniaKey.Up},
            { UrhoKey.Backquote,AvaloniaKey.OemQuotes}
         };
    }

}
